# Generated by Django 5.2.3 on 2025-07-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("in_progress", "In progress"),
                    ("pending_review", "Pending review"),
                    ("completed", "Completed"),
                    ("canceled", "Canceled"),
                ],
                default="open",
                max_length=15,
            ),
        ),
    ]
