# Generated by Django 5.2.3 on 2025-07-09 13:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_alter_task_price"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="client",
            field=models.ForeignKey(
                help_text="User who created the task.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Date and time when the object was created.",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(help_text="Deadline for the task."),
        ),
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(help_text="Detailed description of the task."),
        ),
        migrations.AlterField(
            model_name="task",
            name="freelancer",
            field=models.ForeignKey(
                blank=True,
                help_text="User who is assigned to the task.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="freelancer_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Price for the task.",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("in_progress", "In progress"),
                    ("pending_review", "Pending review"),
                    ("completed", "Completed"),
                    ("canceled", "Canceled"),
                ],
                default="open",
                help_text="Current status of the task.",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(help_text="Title of the task.", max_length=200),
        ),
        migrations.AlterField(
            model_name="task",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Date and time when the object was last updated.",
            ),
        ),
    ]
