# Generated by Django 5.2.3 on 2025-07-10 07:44

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_alter_task_client_alter_task_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("open", "Open"),
                    ("in_progress", "In progress"),
                    ("pending_review", "Pending review"),
                    ("completed", "Completed"),
                    ("canceled", "Canceled"),
                    ("expired", "Expired"),
                ],
                default="open",
                help_text="Current status of the task.",
                max_length=15,
            ),
        ),
    ]
