# Generated by Django 5.2.3 on 2025-07-09 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0001_initial"),
        ("tasks", "0003_alter_task_client_alter_task_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposal",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Date and time when the object was created.",
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="freelancer",
            field=models.ForeignKey(
                help_text="Freelancer who made the proposal.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proposals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="message",
            field=models.TextField(blank=True, help_text="Proposal message."),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                help_text="Current status of the proposal.",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="task",
            field=models.ForeignKey(
                help_text="Task for which the proposal is made.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proposals",
                to="tasks.task",
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Date and time when the object was last updated.",
            ),
        ),
    ]
