# Generated by Django 5.2.3 on 2025-07-10 07:44

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "proposals",
            "0002_alter_proposal_created_at_alter_proposal_freelancer_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposal",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                help_text="Current status of the proposal.",
                max_length=8,
            ),
        ),
    ]
