# Generated by Django 5.2.3 on 2025-07-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="average_rating",
            field=models.FloatField(default=0.0),
        ),
    ]
