# Generated by Django 5.2.3 on 2025-07-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_average_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="average_rating",
            field=models.FloatField(
                default=0.0, help_text="Average rating of the user."
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Date and time when the object was created.",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                help_text="Email address of the user.", max_length=254, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("client", "Client"), ("freelancer", "Freelancer")],
                default="client",
                help_text="Role of the user.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Date and time when the object was last updated.",
            ),
        ),
    ]
