# Generated by Django 5.2.3 on 2025-07-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_average_rating_alter_user_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(
                blank=True, help_text="A short biography of the user."
            ),
        ),
    ]
