# Generated by Django 5.2.3 on 2025-07-08 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="updated_at",
        ),
    ]
