# Generated by Django 5.2.3 on 2025-07-09 13:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_remove_review_updated_at"),
        ("tasks", "0003_alter_task_client_alter_task_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="comment",
            field=models.TextField(blank=True, help_text="Review comment."),
        ),
        migrations.AlterField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Date and time when the review was created.",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.IntegerField(
                help_text="Rating from 1 to 5.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="recipient",
            field=models.ForeignKey(
                help_text="User who received the review.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="reviewer",
            field=models.ForeignKey(
                help_text="User who wrote the review.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="given_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="task",
            field=models.ForeignKey(
                help_text="Task being reviewed.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="tasks.task",
            ),
        ),
    ]
